import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Z-API Central Sidebar Configuration
 *
 * This file governs the structure and navigation of the documentation sidebar.
 * It is organized to provide a logical and intuitive user journey, from initial
 * setup to advanced features.
 *
 * The structure follows a hierarchical pattern:
 * - Top-level documents for key information.
 * - Categories for grouping related topics.
 * - Each item includes a document ID and a custom icon for better visual navigation.
 *
 * When adding a new document, ensure it is placed in the most logical category
 * and that its `sidebar_position` in the markdown file is set correctly.
 */
const sidebars: SidebarsConfig = {
  zapiSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Comece Aqui",
      customProps: { icon: "Rocket" },
    },
    {
      type: "category",
      label: "Início Rápido",
      link: {
        type: "doc",
        id: "quick-start/index",
      },
      collapsed: false,
      customProps: { icon: "PlayCircle" },
      items: [
        "quick-start/introducao",
        "quick-start/colecao-postman",
        "quick-start/bloqueios-e-banimentos",
      ],
    },
    {
      type: "category",
      label: "Gerenciando a Instância",
      link: {
        type: "doc",
        id: "instance/index",
      },
      collapsed: true,
      customProps: { icon: "Smartphone" },
      items: [
        "instance/introducao",
        "instance/me",
        "instance/status",
        "instance/qrcode",
        "instance/reiniciar",
        "instance/desconectar",
        "instance/leitura-automatica",
        "instance/leitura-automatica-status",
        {
          type: "category",
          label: "Configurações do Perfil",
          customProps: { icon: "UserCircle" },
          items: [
            "instance/atualizar-imagem-perfil",
            "instance/atualizar-nome-perfil",
            "instance/atualizar-descricao-perfil",
          ],
        },
        "instance/rejeitar-chamadas",
        "instance/mensagem-ligacao",
        {
          type: "category",
          label: "Dados da Instância",
          customProps: { icon: "Database" },
          items: [
            "instance/dados",
            "instance/dados-celular",
            "instance/renomear",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Mensagens",
      link: {
        type: "doc",
        id: "messages/index",
      },
      collapsed: true,
      customProps: { icon: "MessageSquare" },
      items: [
        "messages/introducao",
        // Basic Messages
        "messages/texto-simples",
        "messages/reencaminhar",
        "messages/reacao",
        // Media
        "messages/imagem",
        "messages/video",
        "messages/audio",
        "messages/documentos",
        "messages/sticker",
        "messages/gif",
        // Interactive Messages
        {
          type: "category",
          label: "Interativas",
          customProps: { icon: "MousePointerClick" },
          items: [
            "messages/botoes",
            "messages/lista-opcoes",
            "messages/texto-botoes-acao",
            "messages/botoes-imagem",
            "messages/botoes-video",
            "messages/carrossel",
          ],
        },
        // Other Types
        "messages/link",
        "messages/localizacao",
        "messages/contato",
        "messages/varios-contatos",
        "messages/enquete",
        // Business
        "messages/produto",
        "messages/catalogo",
        "messages/aprovacao-pedido",
        // Actions
        "messages/deletar",
        "messages/ler",
        "messages/responder",
        "messages/fixar-desafixar",
        // New Features
        "messages/botao-otp",
        "messages/botao-pix",
        "messages/atualizacao-status-pedido",
        "messages/convite-admin-canal",
        "messages/evento",
        "messages/editar-evento",
        "messages/responder-evento",
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      link: {
        type: "doc",
        id: "webhooks/index",
      },
      collapsed: true,
      customProps: { icon: "Webhook" },
      items: [
        "webhooks/introducao",
        "webhooks/ao-receber",
        "webhooks/status-mensagem",
        "webhooks/ao-conectar",
        "webhooks/ao-desconectar",
        "webhooks/chat-presence",
        "webhooks/ao-enviar",
        "webhooks/atualizar-todos",
        "webhooks/atualizar-notificar-enviadas",
      ],
    },
    {
      type: "category",
      label: "Segurança",
      link: {
        type: "doc",
        id: "security/index",
      },
      customProps: { icon: "Shield" },
      collapsed: true,
      items: [
        "security/id-e-token",
        "security/token-seguranca",
        "security/restricao-ip",
        "security/autenticacao-2fa",
      ],
    },
    {
      type: "category",
      label: "Contatos",
      link: {
        type: "doc",
        id: "contacts/index",
      },
      customProps: { icon: "Contact" },
      collapsed: true,
      items: [
        "contacts/introducao",
        "contacts/pegar-contatos",
        "contacts/metadata",
        "contacts/imagem",
        "contacts/numero-whatsapp",
        "contacts/adicionar",
        "contacts/remover",
        "contacts/validar-lote",
        "contacts/bloquear",
        "contacts/denunciar",
      ],
    },
    {
      type: "category",
      label: "Grupos",
      link: {
        type: "doc",
        id: "groups/index",
      },
      customProps: { icon: "Users" },
      collapsed: true,
      items: [
        "groups/introducao",
        "groups/criar",
        "groups/buscar",
        "groups/metadata",
        "groups/metadata-leve",
        "groups/sair",
        "groups/mencionar-membro",
        "groups/mencionar-grupo",
        {
          type: "category",
          label: "Gerenciar Participantes",
          key: "groups/manage-participants",
          customProps: { icon: "UserCog" },
          items: [
            "groups/adicionar-participantes",
            "groups/remover-participantes",
            "groups/promover-admin",
            "groups/remover-admin",
            "groups/aprovar-participantes",
            "groups/rejeitar-participantes",
          ],
        },
        {
          type: "category",
          label: "Configurações do Grupo",
          customProps: { icon: "Settings" },
          items: [
            "groups/atualizar-nome",
            "groups/atualizar-imagem",
            "groups/alterar-descricao",
            "groups/configuracoes",
          ],
        },
        {
          type: "category",
          label: "Convites",
          customProps: { icon: "Mails" },
          items: [
            "groups/obter-link",
            "groups/redefinir-link",
            "groups/aceitar-convite",
            "groups/metadata-convite",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "WhatsApp Business",
      link: {
        type: "doc",
        id: "whatsapp-business/index",
      },
      customProps: { icon: "Briefcase" },
      collapsed: true,
      items: [
        "whatsapp-business/introducao",
        {
          type: "category",
          label: "Produtos e Catálogo",
          customProps: { icon: "ShoppingCart" },
          items: [
            "whatsapp-business/criar-produto",
            "whatsapp-business/pegar-produtos",
            "whatsapp-business/pegar-produtos-telefone",
            "whatsapp-business/pegar-produto-id",
            "whatsapp-business/deletar-produto",
            "whatsapp-business/configuracao-catalogo",
          ],
        },
        {
          type: "category",
          label: "Coleções",
          customProps: { icon: "Folders" },
          items: [
            "whatsapp-business/criar-colecao",
            "whatsapp-business/listar-colecoes",
            "whatsapp-business/editar-colecao",
            "whatsapp-business/deletar-colecao",
            "whatsapp-business/adicionar-produtos-colecao",
            "whatsapp-business/remover-produtos-colecao",
          ],
        },
        {
          type: "category",
          label: "Etiquetas (Labels)",
          customProps: { icon: "Tags" },
          items: [
            "whatsapp-business/buscar-etiquetas",
            "whatsapp-business/criar-etiqueta",
            "whatsapp-business/editar-etiqueta",
            "whatsapp-business/deletar-etiqueta",
            "whatsapp-business/atribuir-etiquetas",
            "whatsapp-business/remover-etiquetas",
          ],
        },
        {
          type: "category",
          label: "Perfil Comercial",
          customProps: { icon: "Building" },
          items: [
            "whatsapp-business/dados-conta",
            "whatsapp-business/alterar-descricao-empresa",
            "whatsapp-business/alterar-endereco-empresa",
            "whatsapp-business/alterar-email-empresa",
            "whatsapp-business/alterar-websites-empresa",
            "whatsapp-business/alterar-horario-funcionamento",
            "whatsapp-business/atribuir-categorias",
          ],
        },
        "whatsapp-business/atribuir-anotacoes",
      ],
    },
    {
      type: "category",
      label: "Chats",
      link: {
        type: "doc",
        id: "chats/index",
      },
      customProps: { icon: "MessageCircle" },
      collapsed: true,
      items: [
        "chats/introducao",
        "chats/pegar",
        "chats/metadata",
        "chats/ler",
        "chats/arquivar",
        "chats/fixar",
        "chats/mutar",
        "chats/limpar",
        "chats/deletar",
        "chats/expiracao",
      ],
    },
    {
      type: "category",
      label: "Status",
      link: {
        type: "doc",
        id: "status/index",
      },
      customProps: { icon: "CircleDashed" },
      collapsed: true,
      items: [
        "status/introducao",
        "status/enviando-texto",
        "status/enviando-imagem",
        "status/enviando-video",
        "status/responder-texto",
        "status/responder-gif",
        "status/responder-sticker",
      ],
    },
    {
      type: "category",
      label: "Privacidade",
      link: {
        type: "doc",
        id: "privacy/index",
      },
      customProps: { icon: "Lock" },
      collapsed: true,
      items: [
        "privacy/introducao",
        "privacy/visto-por-ultimo",
        "privacy/visualizacao-foto-perfil",
        "privacy/visualizacao-recado",
        "privacy/confirmacoes-leitura",
        "privacy/permissao-adicionar-grupos",
        "privacy/contatos-nao-permitidos",
        "privacy/visualizacao-online",
        "privacy/duracao-mensagens",
      ],
    },
    {
      type: "category",
      label: "Fila de Mensagens",
      link: {
        type: "doc",
        id: "message-queue/index",
      },
      customProps: { icon: "List" },
      collapsed: true,
      items: [
        "message-queue/introducao",
        "message-queue/fila",
        "message-queue/apagar-fila",
        "message-queue/apagar-mensagem",
      ],
    },
    {
      type: "category",
      label: "Dicas e Troubleshooting",
      link: {
        type: "doc",
        id: "tips/index",
      },
      collapsed: true,
      customProps: { icon: "Lightbulb" },
      items: [
        "tips/bloqueios-e-banimentos",
        "tips/bloqueios-e-banimentos-2025",
        "tips/funcionamento-botoes",
        "tips/lid",
        "tips/colecao-postman",
        "tips/expiracao-arquivos",
        "tips/z-api-vs-api-oficial",
        "tips/habilitar-numero-fixo",
        "tips/emuladores",
        "tips/estabilidade",
        "tips/android-sempre-ativo",
        "tips/bloqueio-tela",
      ],
    },
    {
      type: "category",
      label: "Multi-Devices",
      link: {
        type: "doc",
        id: "multi-devices/index",
      },
      collapsed: true,
      customProps: { icon: "Smartphone" },
      items: ["multi-devices/introducao", "multi-devices/beta"],
    },
    {
      type: "category",
      label: "Comunidades",
      link: {
        type: "doc",
        id: "communities/index",
      },
      collapsed: true,
      customProps: { icon: "LayoutGrid" },
      items: [
        "communities/introducao",
        "communities/criar",
        "communities/listar",
        "communities/metadata",
        "communities/desativar",
        {
          type: "category",
          label: "Gerenciar Participantes",
          key: "communities/manage-participants",
          customProps: { icon: "UserCog" },
          items: [
            "communities/adicionar-participantes",
            "communities/remover-participantes",
            "communities/promover-admin",
            "communities/remover-admin",
          ],
        },
        {
          type: "category",
          label: "Gerenciar Grupos",
          customProps: { icon: "Users" },
          items: [
            "communities/vincular-grupos",
            "communities/desvincular-grupos",
          ],
        },
        {
          type: "category",
          label: "Configurações",
          customProps: { icon: "Settings" },
          items: [
            "communities/alterar-descricao",
            "communities/configuracoes",
            "communities/redefinir-link",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Newsletter",
      link: {
        type: "doc",
        id: "newsletter/index",
      },
      collapsed: true,
      customProps: { icon: "Newspaper" },
      items: [
        "newsletter/introducao",
        "newsletter/criar-canal",
        "newsletter/atualizar-imagem",
        "newsletter/atualizar-nome",
        "newsletter/atualizar-descricao",
        "newsletter/seguir-canal",
        "newsletter/deixar-seguir",
        "newsletter/silenciar-canal",
        "newsletter/reativar-som",
        "newsletter/deletar-canal",
        "newsletter/metadata-canal",
        "newsletter/listar-canais",
        "newsletter/buscar-canais",
        "newsletter/configuracoes-canal",
        "newsletter/aceitar-admin",
        "newsletter/remover-admin",
        "newsletter/revogar-convite-admin",
        "newsletter/transferir-propriedade",
      ],
    },
    {
      type: "category",
      label: "Lista de Transmissão",
      link: {
        type: "doc",
        id: "transmission-list/index",
      },
      collapsed: true,
      customProps: { icon: "ListChecks" },
      items: [
        "transmission-list/introducao",
        // 'transmission-list/criar',
        // 'transmission-list/enviar',
        // 'transmission-list/gerenciar',
      ],
    },
    {
      type: "category",
      label: "Chamadas",
      link: {
        type: "doc",
        id: "calls/index",
      },
      collapsed: true,
      customProps: { icon: "Phone" },
      items: ["calls/introducao", "calls/fazer-ligacao"],
    },
    {
      type: "category",
      label: "Mobile",
      link: {
        type: "doc",
        id: "mobile/index",
      },
      collapsed: true,
      customProps: { icon: "Smartphone" },
      items: [
        "mobile/introducao",
        "mobile/verificar-disponibilidade",
        "mobile/solicitar-codigo",
        "mobile/confirmar-codigo",
        {
          type: "category",
          label: "Gerenciar Email",
          customProps: { icon: "Mails" },
          items: [
            "mobile/buscar-email",
            "mobile/cadastrar-email",
            "mobile/remover-email",
            "mobile/verificar-email",
          ],
        },
        {
          type: "category",
          label: "Gerenciar Código PIN",
          customProps: { icon: "KeyRound" },
          items: [
            "mobile/verificar-codigo-pin",
            "mobile/cadastrar-codigo-pin",
            "mobile/confirmar-codigo-pin",
            "mobile/recuperacao-codigo-pin",
            "mobile/remover-codigo-pin",
          ],
        },
        {
          type: "category",
          label: "Outros",
          customProps: { icon: "MoreHorizontal" },
          items: ["mobile/responder-captcha", "mobile/solicitar-desbanimento"],
        },
      ],
    },
    {
      type: "category",
      label: "Meta AI",
      link: {
        type: "doc",
        id: "meta-ai/index",
      },
      collapsed: true,
      customProps: { icon: "Cpu" },
      items: ["meta-ai/introducao", "meta-ai/conversar"],
    },
    {
      type: "category",
      label: "Partner API",
      link: {
        type: "doc",
        id: "partners/index",
      },
      collapsed: true,
      customProps: { icon: "Handshake" },
      items: [
        "partners/introducao",
        "partners/criar-instancia",
        "partners/listar-instancias",
        "partners/assinar-instancia",
        "partners/cancelar-instancia",
      ],
    },
    {
      type: "category",
      label: "Integradores",
      link: {
        type: "doc",
        id: "integradors/index",
      },
      collapsed: true,
      customProps: { icon: "Puzzle" },
      items: ["integradors/introducao", "integradors/encontrar-meu-pacote"],
    },
    {
      type: "category",
      label: "Arquitetura",
      link: {
        type: "doc",
        id: "architecture/index",
      },
      collapsed: true,
      customProps: { icon: "Network" },
      items: ["architecture/overview"],
    },
  ],
};

export default sidebars;
